### ISSUE TITLE
Type error: 'Map' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by in-ch** [JaeSeoKim/kakao.maps.d.ts#10]
```
Type error: 'Map' cannot be used as a JSX component.
  Its return type 'ReactNode' is not a valid JSX element.
    Type 'string' is not assignable to type 'ReactElement<any, any>'.
```

next.js 프로젝트에서 빌드 시 다음과 같은 에러가 납니다. 
로컬에서는 잘 작동하는데 ec2 Amazon linux 환경에서 빌드 시 다음과 같은 에러가 나네요... 
혹시 해결 방법이 있을까요? 

node: v18.10.0

**Comment by JaeSeoKim** [comment]
해당 이슈는 해당 타입정의 라이브러리에서 문제가 발생한 부분이 아니므로 close 처리 하였습니다.

https://github.com/JaeSeoKim/react-kakao-maps-sdk/issues/57
